name: CustomGen
version: 1.0
api-version: 1.19
author: Phil McFly
main: net.universestudio.CustomGen
commands:
  customgen:
    description: Base command
    permission: customgen.use

  customgen give:
    description: Gives you a custom gen
    permission: customgen.give
